### ISSUE TITLE
Thank you very much for the list

### ISSUE THREAD

**Issue by asigalov61** [vibertthio/awesome-machine-learning-art#3]
Hey Vibert,

Thank you so much for this amazing list. It's so awesome to know that there are so many people/projects dedicated to art/music AI.

I was wondering if you can add my repos/SoundCloud/Artworks to your curated list. It will really help me out to continue my work.

Here is my AI art: https://fineartamerica.com/profiles/aleksandr-sigalov

I also wanted to talk to you in private about one project so if you can contact me via email (if you can/have time) it will be much appreciated.

Thank you.

Alex

P.S. Also thank you so much for your great front-end/interface for the REMI Pop-music transformer. It's amazing.

**Comment by vibertthio** [comment]
Sure. Please just open a PR including the link and the description! You can find my mail via my website. ☺️
